In [1]:
!pip install sqlalchemy psycopg2-binary -q

In [2]:
from sqlalchemy import create_engine, inspect
import pandas as pd

In [ ]:
username = 'postgres'
password = 'postgres'
host = 'localhost'
port = 5432
database = 'world'

engine = create_engine(f'postgresql://{username}:{password}@{host}/{database}')
# sqlite_db_path = r'C:\\path\to\example.db'
# engine = create_engine(f'sqlite:///{sqlite_db_path}')
inspector = inspect(engine)
inspector.get_table_names()

['city', 'country', 'countrylanguage']

In [4]:
query = """
SELECT *
FROM countrylanguage
LIMIT 5
"""

res = pd.read_sql_query(query, con=engine)
res

  countrycode    language  isofficial  percentage
0         AFG      Pashto        True        52.4
1         NLD       Dutch        True        95.6
2         ANT  Papiamento        True        86.2
3         ALB   Albaniana        True        97.9
4         DZA      Arabic        True        86.0

In [5]:
table_name = 'country'
df_table = pd.read_sql_table(table_name, con=engine)
df_table

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
3,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
4,DZA,Algeria,Africa,Northern Africa,2381741.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the UK,Elisabeth II,NaN,IO
235,SGS,South Georgia and the South Sandwich Islands,Antarctica,Antarctica,3903.0,NaN,0,NaN,0.0,NaN,South Georgia and the South Sandwich Islands,Dependent Territory of the UK,Elisabeth II,NaN,GS
236,HMD,Heard Island and McDonald Islands,Antarctica,Antarctica,359.0,NaN,0,NaN,0.0,NaN,Heard and McDonald Islands,Territory of Australia,Elisabeth II,NaN,HM
237,ATF,French Southern territories,Antarctica,Antarctica,7780.0,NaN,0,NaN,0.0,NaN,Terres australes françaises,Nonmetropolitan Territory of France,Jacques Chirac,NaN,TF
238,UMI,United States Minor Outlying Islands,Oceania,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,United States Minor Outlying Islands,Dependent Territory of the US,George W. Bush,NaN,UM