In [2]:
import pandas as pd

In [3]:
from sqlalchemy import create_engine

query_emp = """
SELECT * 
FROM employees   
limit 100;
"""
query_sal = """
SELECT * 
FROM salaries  
limit 100;
"""

con = create_engine("postgresql+psycopg2://postgres:postgres@localhost/employees")

df_emp = pd.read_sql_query(query_emp, con)
df_sal = pd.read_sql_query(query_sal, con)

In [7]:
df_emp.tail(3)

    emp_no  birth_date   first_name  last_name gender   hire_date
97   10098  1961-09-23  Sreekrishna  Servieres      F  1985-05-13
98   10099  1956-05-25       Valter    Sullins      F  1988-10-18
99   10100  1953-04-21     Hironobu  Haraldson      F  1987-09-21

In [6]:
df_sal.head(3)

   emp_no  salary   from_date     to_date
0   10001   60117  1986-06-26  1987-06-26
1   10001   62102  1987-06-26  1988-06-25
2   10001   66074  1988-06-25  1989-06-25

In [9]:
df_merged = pd.merge(
	df_emp, df_sal, how='left', on='emp_no'
)
df_merged

,emp_no,birth_date,first_name,last_name,gender,hire_date,salary,from_date,to_date
0,10001,1953-09-02,Georgi,Facello,M,1986-06-26,60117.0,1986-06-26,1987-06-26
1,10001,1953-09-02,Georgi,Facello,M,1986-06-26,62102.0,1987-06-26,1988-06-25
2,10001,1953-09-02,Georgi,Facello,M,1986-06-26,66074.0,1988-06-25,1989-06-25
3,10001,1953-09-02,Georgi,Facello,M,1986-06-26,66596.0,1989-06-25,1990-06-25
4,10001,1953-09-02,Georgi,Facello,M,1986-06-26,66961.0,1990-06-25,1991-06-25
...,...,...,...,...,...,...,...,...,...
186,10096,1954-09-16,Jayson,Mandell,M,1990-01-14,NaN,NaN,NaN
187,10097,1952-02-27,Remzi,Waschkowski,M,1990-09-15,NaN,NaN,NaN
188,10098,1961-09-23,Sreekrishna,Servieres,F,1985-05-13,NaN,NaN,NaN
189,10099,1956-05-25,Valter,Sullins,F,1988-10-18,NaN,NaN,NaN
190,10100,1953-04-21,Hironobu,Haraldson,F,1987-09-21,NaN,NaN,NaN

In [10]:
pd.concat([df_emp, df_sal], axis=0)

,emp_no,birth_date,first_name,last_name,gender,hire_date,salary,from_date,to_date
0,10001,1953-09-02,Georgi,Facello,M,1986-06-26,NaN,NaN,NaN
1,10002,1964-06-02,Bezalel,Simmel,F,1985-11-21,NaN,NaN,NaN
2,10003,1959-12-03,Parto,Bamford,M,1986-08-28,NaN,NaN,NaN
3,10004,1954-05-01,Chirstian,Koblick,M,1986-12-01,NaN,NaN,NaN
4,10005,1955-01-21,Kyoichi,Maliniak,M,1989-09-12,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
95,10009,NaN,NaN,NaN,NaN,NaN,74612.0,1992-02-17,1993-02-16
96,10009,NaN,NaN,NaN,NaN,NaN,76518.0,1993-02-16,1994-02-16
97,10009,NaN,NaN,NaN,NaN,NaN,78335.0,1994-02-16,1995-02-16
98,10009,NaN,NaN,NaN,NaN,NaN,80944.0,1995-02-16,1996-02-16
99,10009,NaN,NaN,NaN,NaN,NaN,82507.0,1996-02-16,1997-02-15

In [23]:
pd.concat([df_emp[['emp_no']], df_sal[['emp_no']]], axis=0)['emp_no'].unique()

array([10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008, 10009,
       10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017, 10018,
       10019, 10020, 10021, 10022, 10023, 10024, 10025, 10026, 10027,
       10028, 10029, 10030, 10031, 10032, 10033, 10034, 10035, 10036,
       10037, 10038, 10039, 10040, 10041, 10042, 10043, 10044, 10045,
       10046, 10047, 10048, 10049, 10050, 10051, 10052, 10053, 10054,
       10055, 10056, 10057, 10058, 10059, 10060, 10061, 10062, 10063,
       10064, 10065, 10066, 10067, 10068, 10069, 10070, 10071, 10072,
       10073, 10074, 10075, 10076, 10077, 10078, 10079, 10080, 10081,
       10082, 10083, 10084, 10085, 10086, 10087, 10088, 10089, 10090,
       10091, 10092, 10093, 10094, 10095, 10096, 10097, 10098, 10099,
       10100])

In [25]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\user\miniconda3\envs\ds\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\user\miniconda3\envs\ds\Lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\user\miniconda3\envs\ds\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\user\miniconda3\envs\ds\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\user\miniconda3\envs\ds\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
# column, attribute, feature

In [39]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [30]:
housing['data'].shape

(20640, 8)

In [31]:
import numpy as np

In [33]:
housing['target'][:,np.newaxis]

array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]], shape=(20640, 1))

In [37]:
housing_data = np.concat([housing['data'], housing['target'][:,np.newaxis]], axis=1)

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude',
 'MedHouseVal']

In [48]:
df = pd.DataFrame(data=housing_data, 
columns=housing['feature_names'] + housing['target_names']
)
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [52]:
df = pd.read_csv(r"..\test\housing.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [81]:
df.groupby('ocean_proximity').agg({
	'median_income': 'min',
	'median_income': 'max',
})

                 median_income
ocean_proximity
<1H OCEAN              15.0001
INLAND                 15.0001
ISLAND                  3.3906
NEAR BAY               15.0001
NEAR OCEAN             15.0001

In [80]:
df.groupby('ocean_proximity').agg(
	median_income_min = ('median_income', 'min'),
	median_income_max = ('median_income', 'max'),
)

                 median_income_min  median_income_max
ocean_proximity
<1H OCEAN                   0.4999            15.0001
INLAND                      0.4999            15.0001
ISLAND                      2.1579             3.3906
NEAR BAY                    0.4999            15.0001
NEAR OCEAN                  0.5360            15.0001

In [55]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [64]:
# SELECT ocean_proximity, avg(median_house_value) 
# FROM TABLE 
# GROUP BY ocean_proximity

for x,y in df.groupby(by='ocean_proximity'):
	print(type(x), type(y), x)
	break

<class 'str'> <class 'pandas.DataFrame'> <1H OCEAN

In [70]:
df.groupby(by='ocean_proximity')['median_house_value'].mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [83]:
df.groupby('ocean_proximity')['median_income'].transform('mean')

0        4.172885
1        4.172885
2        4.172885
3        4.172885
4        4.172885
           ...
20635    3.208996
20636    3.208996
20637    3.208996
20638    3.208996
20639    3.208996
Name: median_income, Length: 20640, dtype: float64

In [84]:
df.groupby('ocean_proximity')['median_income'].aggregate('mean')

ocean_proximity
<1H OCEAN     4.230682
INLAND        3.208996
ISLAND        2.744420
NEAR BAY      4.172885
NEAR OCEAN    4.005785
Name: median_income, dtype: float64

In [85]:
df.head(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY

In [86]:
df.groupby('ocean_proximity').agg({
	'longitude' : 'mean',
	'latitude' : 'min'
})

                  longitude  latitude
ocean_proximity
<1H OCEAN       -118.847766     32.61
INLAND          -119.732990     32.64
ISLAND          -118.354000     33.33
NEAR BAY        -122.260694     37.35
NEAR OCEAN      -119.332555     32.54

In [98]:
def f(balaca_df):
	print(type(balaca_df), balaca_df.shape)
	# return balaca_df['longitude'].mean() - balaca_df['latitude'].min()

df.groupby('ocean_proximity').agg(f)

<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)
<class 'pandas.Series'> (9136,)
<class 'pandas.Series'> (6551,)
<class 'pandas.Series'> (5,)
<class 'pandas.Series'> (2290,)
<class 'pandas.Series'> (2658,)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
ocean_proximity,,,,,,,,,
<1H OCEAN,None,None,None,None,None,None,None,None,None
INLAND,None,None,None,None,None,None,None,None,None
ISLAND,None,None,None,None,None,None,None,None,None
NEAR BAY,None,None,None,None,None,None,None,None,None
NEAR OCEAN,None,None,None,None,None,None,None,None,None

In [94]:
y

       longitude  latitude
100      -117.04     32.80
103      -118.47     33.99
104      -121.77     37.33
105      -118.50     33.97
107      -118.39     34.08
...          ...       ...
20532    -117.96     33.78
20533    -118.40     33.92
20536    -122.01     37.32
20537    -121.92     37.31
20539    -117.95     33.86

[9136 rows x 2 columns]

In [99]:
df.groupby('ocean_proximity')['median_income'].filter(lambda ser: ser > ser.mean())

TypeError: the filter must return a boolean result

In [107]:
import seaborn as sns

In [110]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [129]:
g = df.groupby(['sex', 'class'])['survived'].mean()
g = g.to_frame()
g

               survived
sex    class
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [133]:
g.droplevel(0, 0).loc['Second', :]

        survived
class
Second  0.921053
Second  0.157407

In [131]:
g.loc[['female', 'Second'], :]

KeyError: "['Second'] not in index"

In [119]:
g.unstack()

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [115]:
pd.pivot_table(df, values='survived', index='sex', columns='class', aggfunc='mean')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447