In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

In [24]:
df = pd.read_csv(r"C:\Users\user\Desktop\div\data\files\car-sales-extended-missing-data.csv")
df

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [18]:
fv = df['Make'].value_counts().idxmax()
fv

'Toyota'

In [25]:
df['Make'] = df['Make'].fillna(fv)
df

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996  Toyota  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [26]:
df.loc[df['Make'].isnull(), :]

Empty DataFrame
Columns: [Make, Colour, Odometer (KM), Doors, Price]
Index: []

In [22]:
df

       Make Colour  Odometer (KM)  Doors    Price
0       NaN  White        35431.0    4.0  15323.0
1       NaN   Blue       192714.0    5.0  19943.0
2       NaN  White        84714.0    4.0  28343.0
3       NaN  White       154365.0    4.0  13434.0
4       NaN   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995     NaN  Black        35820.0    4.0  32042.0
996  Toyota  White       155144.0    3.0   5716.0
997     NaN   Blue        66604.0    4.0  31570.0
998     NaN  White       215883.0    4.0   4001.0
999     NaN   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [33]:
mask = df.isnull().any(axis=1)
df[mask]

       Make Colour  Odometer (KM)  Doors    Price
7     Honda  White            NaN    4.0  20306.0
20   Toyota    NaN       124844.0    4.0  24130.0
21    Honda    NaN        30615.0    4.0  29653.0
31   Toyota  White       108569.0    NaN   6866.0
37   Nissan  White            NaN    4.0  15131.0
..      ...    ...            ...    ...      ...
960   Honda  White            NaN    4.0  13070.0
968  Nissan  White       227278.0    4.0      NaN
972   Honda  White            NaN    4.0  17939.0
975   Honda    NaN        22409.0    4.0  10429.0
983  Toyota    Red            NaN    4.0  14671.0

[184 rows x 5 columns]

In [37]:
df

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996  Toyota  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [39]:
def f(x):
	if x > 15000:
		return x*1.2
	else:
		return x

df['Price2'] = df['Price'].apply(f)
df

       Make Colour  Odometer (KM)  Doors    Price    Price2
0     Honda  White        35431.0    4.0  18387.6  22065.12
1       BMW   Blue       192714.0    5.0  23931.6  28717.92
2     Honda  White        84714.0    4.0  34011.6  40813.92
3    Toyota  White       154365.0    4.0  13434.0  13434.00
4    Nissan   Blue       181577.0    3.0  14043.0  14043.00
..      ...    ...            ...    ...      ...       ...
995  Toyota  Black        35820.0    4.0  38450.4  46140.48
996  Toyota  White       155144.0    3.0   5716.0   5716.00
997  Nissan   Blue        66604.0    4.0  37884.0  45460.80
998   Honda  White       215883.0    4.0   4001.0   4001.00
999  Toyota   Blue       248360.0    4.0  12732.0  12732.00

[1000 rows x 6 columns]

In [47]:
# df.head()
# df.tail(5)
df.sort_index(ascending=False).iloc[:3, :]

       Make Colour  Odometer (KM)  Doors    Price   Price2
999  Toyota   Blue       248360.0    4.0  12732.0  12732.0
998   Honda  White       215883.0    4.0   4001.0   4001.0
997  Nissan   Blue        66604.0    4.0  37884.0  45460.8

In [52]:
df["Make"].to_dict()

{0: 'Honda',
 1: 'BMW',
 2: 'Honda',
 3: 'Toyota',
 4: 'Nissan',
 5: 'Honda',
 6: 'Toyota',
 7: 'Honda',
 8: 'Toyota',
 9: 'Honda',
 10: 'Nissan',
 11: 'Nissan',
 12: 'Nissan',
 13: 'Toyota',
 14: 'Honda',
 15: 'Toyota',
 16: 'Toyota',
 17: 'BMW',
 18: 'Nissan',
 19: 'Nissan',
 20: 'Toyota',
 21: 'Honda',
 22: 'Toyota',
 23: 'Honda',
 24: 'Honda',
 25: 'Honda',
 26: 'Honda',
 27: 'Honda',
 28: 'Honda',
 29: 'Toyota',
 30: 'Nissan',
 31: 'Toyota',
 32: 'Nissan',
 33: 'Nissan',
 34: 'Honda',
 35: 'Honda',
 36: 'Nissan',
 37: 'Nissan',
 38: 'Nissan',
 39: 'Toyota',
 40: 'Toyota',
 41: 'Toyota',
 42: 'Honda',
 43: 'Toyota',
 44: 'Toyota',
 45: 'Nissan',
 46: 'Toyota',
 47: 'Toyota',
 48: 'Nissan',
 49: 'Toyota',
 50: 'Toyota',
 51: 'Honda',
 52: 'Toyota',
 53: 'Toyota',
 54: 'Toyota',
 55: 'BMW',
 56: 'Honda',
 57: 'BMW',
 58: 'Toyota',
 59: 'Toyota',
 60: 'BMW',
 61: 'Honda',
 62: 'Honda',
 63: 'Honda',
 64: 'Toyota',
 65: 'BMW',
 66: 'Toyota',
 67: 'Toyota',
 68: 'Toyota',
 69: 'BMW',
 70: 'Nissan',
 71: 'Toyota',
 72: 'Honda',
 73: 'Toyota',
 74: 'Toyota',
 75: 'Toyota',
 76: 'Toyota',
 77: 'Toyota',
 78: 'Toyota',
 79: 'Honda',
 80: 'Honda',
 81: 'Toyota',
 82: 'Nissan',
 83: 'Toyota',
 84: 'Toyota',
 85: 'Nissan',
 86: 'Nissan',
 87: 'Honda',
 88: 'Nissan',
 89: 'Toyota',
 90: 'Nissan',
 91: 'Toyota',
 92: 'Honda',
 93: 'Honda',
 94: 'Honda',
 95: 'Honda',
 96: 'Toyota',
 97: 'Toyota',
 98: 'Toyota',
 99: 'Honda',
 100: 'Honda',
 101: 'Toyota',
 102: 'Honda',
 103: 'Honda',
 104: 'Honda',
 105: 'Honda',
 106: 'Toyota',
 107: 'Honda',
 108: 'Nissan',
 109: 'Honda',
 110: 'Toyota',
 111: 'Nissan',
 112: 'Nissan',
 113: 'Nissan',
 114: 'Nissan',
 115: 'Toyota',
 116: 'Toyota',
 117: 'Nissan',
 118: 'Nissan',
 119: 'BMW',
 120: 'Nissan',
 121: 'Nissan',
 122: 'Toyota',
 123: 'Toyota',
 124: 'Nissan',
 125: 'Toyota',
 126: 'Toyota',
 127: 'BMW',
 128: 'Nissan',
 129: 'Toyota',
 130: 'Nissan',
 131: 'Toyota',
 132: 'Toyota',
 133: 'Honda',
 134: 'Toyota',
 135: 'Honda',
 136: 'Toyota',
 137: 'Honda',
 138: 'Toyota',
 139: 'Honda',
 140: 'Nissan',
 141: 'Toyota',
 142: 'Honda',
 143: 'Nissan',
 144: 'BMW',
 145: 'Nissan',
 146: 'BMW',
 147: 'Toyota',
 148: 'Toyota',
 149: 'Toyota',
 150: 'Nissan',
 151: 'Honda',
 152: 'Toyota',
 153: 'Nissan',
 154: 'Nissan',
 155: 'BMW',
 156: 'Toyota',
 157: 'Toyota',
 158: 'Toyota',
 159: 'Honda',
 160: 'Honda',
 161: 'BMW',
 162: 'Honda',
 163: 'Honda',
 164: 'Nissan',
 165: 'Nissan',
 166: 'Honda',
 167: 'Honda',
 168: 'Nissan',
 169: 'Nissan',
 170: 'Toyota',
 171: 'Toyota',
 172: 'Honda',
 173: 'Nissan',
 174: 'Toyota',
 175: 'Toyota',
 176: 'Toyota',
 177: 'Toyota',
 178: 'Honda',
 179: 'BMW',
 180: 'Toyota',
 181: 'Nissan',
 182: 'Toyota',
 183: 'Toyota',
 184: 'Nissan',
 185: 'Nissan',
 186: 'Honda',
 187: 'Toyota',
 188: 'Honda',
 189: 'BMW',
 190: 'Toyota',
 191: 'Honda',
 192: 'Toyota',
 193: 'Toyota',
 194: 'Honda',
 195: 'Toyota',
 196: 'Honda',
 197: 'Toyota',
 198: 'Nissan',
 199: 'Honda',
 200: 'Toyota',
 201: 'Honda',
 202: 'Honda',
 203: 'Toyota',
 204: 'Nissan',
 205: 'Toyota',
 206: 'Honda',
 207: 'Nissan',
 208: 'Toyota',
 209: 'Honda',
 210: 'Toyota',
 211: 'Honda',
 212: 'Honda',
 213: 'Honda',
 214: 'BMW',
 215: 'BMW',
 216: 'Honda',
 217: 'Toyota',
 218: 'Nissan',
 219: 'Toyota',
 220: 'BMW',
 221: 'Nissan',
 222: 'Honda',
 223: 'Toyota',
 224: 'Honda',
 225: 'Toyota',
 226: 'Toyota',
 227: 'BMW',
 228: 'Toyota',
 229: 'BMW',
 230: 'Nissan',
 231: 'Honda',
 232: 'Toyota',
 233: 'Toyota',
 234: 'Honda',
 235: 'Toyota',
 236: 'Honda',
 237: 'Honda',
 238: 'BMW',
 239: 'Toyota',
 240: 'Honda',
 241: 'Nissan',
 242: 'Toyota',
 243: 'Nissan',
 244: 'Honda',
 245: 'Honda',
 246: 'Toyota',
 247: 'Toyota',
 248: 'BMW',
 249: 'BMW',
 250: 'BMW',
 251: 'Toyota',
 252: 'Honda',
 253: 'Toyota',
 254: 'Nissan',
 255: 'Nissan',
 256: 'Toyota',
 257: 'Nissan',
 258: 'Nissan',
 259: 'Honda',
 260: 'Toyota',
 261: 'Toyota',
 262: 'Honda',
 263: 'Honda',
 264: 'Toyota',
 265: 'Toyota',
 266: 'Honda',
 267: 'Honda',
 268: 'BMW',
 269: 'Nissan',
 270: 'Honda',
 271: 'Honda',
 272: 'BMW',
 273: 'Toyota',
 274: 'Toyota',
 275: 'Nissan',
 276: 'Honda',
 277: 'BMW',
 278: 'Honda',
 279: 'Toyota',
 280: 'Nissan',
 281: 'BMW',
 282: 'Honda',
 283: 'Toyota',
 284: 'Honda',
 285: 'Toyota',
 286: 'Honda',
 287: 'Nissan',
 288: 'Honda',
 289: 'Nissan',
 290: 'Toyota',
 291: 'Honda',
 292: 'Toyota',
 293: 'Honda',
 294: 'Toyota',
 295: 'Honda',
 296: 'Nissan',
 297: 'Toyota',
 298: 'Toyota',
 299: 'Toyota',
 300: 'Nissan',
 301: 'Toyota',
 302: 'Honda',
 303: 'Toyota',
 304: 'Toyota',
 305: 'Honda',
 306: 'Honda',
 307: 'Nissan',
 308: 'BMW',
 309: 'Toyota',
 310: 'Toyota',
 311: 'Toyota',
 312: 'Toyota',
 313: 'BMW',
 314: 'Nissan',
 315: 'Toyota',
 316: 'Toyota',
 317: 'Honda',
 318: 'Honda',
 319: 'Nissan',
 320: 'Toyota',
 321: 'Honda',
 322: 'Toyota',
 323: 'Toyota',
 324: 'Toyota',
 325: 'Toyota',
 326: 'Toyota',
 327: 'BMW',
 328: 'Toyota',
 329: 'Nissan',
 330: 'Toyota',
 331: 'Toyota',
 332: 'Nissan',
 333: 'Nissan',
 334: 'Honda',
 335: 'Toyota',
 336: 'Toyota',
 337: 'Honda',
 338: 'Honda',
 339: 'Toyota',
 340: 'Honda',
 341: 'Toyota',
 342: 'Toyota',
 343: 'Honda',
 344: 'Toyota',
 345: 'Toyota',
 346: 'Honda',
 347: 'Nissan',
 348: 'Toyota',
 349: 'BMW',
 350: 'Honda',
 351: 'Toyota',
 352: 'Honda',
 353: 'Toyota',
 354: 'Honda',
 355: 'Honda',
 356: 'Toyota',
 357: 'Nissan',
 358: 'BMW',
 359: 'Toyota',
 360: 'Honda',
 361: 'Toyota',
 362: 'Toyota',
 363: 'Toyota',
 364: 'Honda',
 365: 'Nissan',
 366: 'Honda',
 367: 'Honda',
 368: 'Toyota',
 369: 'Toyota',
 370: 'Honda',
 371: 'Toyota',
 372: 'Honda',
 373: 'Toyota',
 374: 'Toyota',
 375: 'Toyota',
 376: 'Nissan',
 377: 'Honda',
 378: 'Nissan',
 379: 'Honda',
 380: 'Nissan',
 381: 'Toyota',
 382: 'Toyota',
 383: 'Honda',
 384: 'Honda',
 385: 'Honda',
 386: 'Nissan',
 387: 'Nissan',
 388: 'Honda',
 389: 'Toyota',
 390: 'Toyota',
 391: 'Toyota',
 392: 'Toyota',
 393: 'Toyota',
 394: 'BMW',
 395: 'Toyota',
 396: 'Toyota',
 397: 'Toyota',
 398: 'Toyota',
 399: 'BMW',
 400: 'Toyota',
 401: 'Honda',
 402: 'Honda',
 403: 'Nissan',
 404: 'Toyota',
 405: 'BMW',
 406: 'Honda',
 407: 'Honda',
 408: 'Toyota',
 409: 'Toyota',
 410: 'Toyota',
 411: 'BMW',
 412: 'BMW',
 413: 'Toyota',
 414: 'Toyota',
 415: 'Honda',
 416: 'Honda',
 417: 'Honda',
 418: 'Nissan',
 419: 'Honda',
 420: 'Toyota',
 421: 'Toyota',
 422: 'Toyota',
 423: 'Nissan',
 424: 'Toyota',
 425: 'Toyota',
 426: 'Toyota',
 427: 'BMW',
 428: 'Toyota',
 429: 'Toyota',
 430: 'Nissan',
 431: 'BMW',
 432: 'Toyota',
 433: 'Honda',
 434: 'Toyota',
 435: 'Honda',
 436: 'BMW',
 437: 'Nissan',
 438: 'Toyota',
 439: 'Toyota',
 440: 'Honda',
 441: 'Nissan',
 442: 'Nissan',
 443: 'Toyota',
 444: 'Honda',
 445: 'Toyota',
 446: 'Nissan',
 447: 'Toyota',
 448: 'Toyota',
 449: 'Honda',
 450: 'Honda',
 451: 'BMW',
 452: 'Honda',
 453: 'Toyota',
 454: 'Honda',
 455: 'Honda',
 456: 'Toyota',
 457: 'Honda',
 458: 'Toyota',
 459: 'Toyota',
 460: 'Honda',
 461: 'BMW',
 462: 'Toyota',
 463: 'Toyota',
 464: 'Honda',
 465: 'Toyota',
 466: 'Nissan',
 467: 'Honda',
 468: 'Toyota',
 469: 'Honda',
 470: 'Toyota',
 471: 'Nissan',
 472: 'Toyota',
 473: 'Toyota',
 474: 'Nissan',
 475: 'Honda',
 476: 'Toyota',
 477: 'Toyota',
 478: 'Nissan',
 479: 'Nissan',
 480: 'Toyota',
 481: 'Toyota',
 482: 'Nissan',
 483: 'Toyota',
 484: 'Toyota',
 485: 'Toyota',
 486: 'Nissan',
 487: 'Toyota',
 488: 'BMW',
 489: 'Toyota',
 490: 'Toyota',
 491: 'Toyota',
 492: 'Toyota',
 493: 'Honda',
 494: 'Nissan',
 495: 'BMW',
 496: 'Toyota',
 497: 'Nissan',
 498: 'Honda',
 499: 'Nissan',
 500: 'Honda',
 501: 'Honda',
 502: 'Toyota',
 503: 'Toyota',
 504: 'Toyota',
 505: 'Toyota',
 506: 'Toyota',
 507: 'Toyota',
 508: 'Nissan',
 509: 'Nissan',
 510: 'Toyota',
 511: 'BMW',
 512: 'Nissan',
 513: 'Toyota',
 514: 'Nissan',
 515: 'Honda',
 516: 'Toyota',
 517: 'Toyota',
 518: 'Honda',
 519: 'Honda',
 520: 'Nissan',
 521: 'Nissan',
 522: 'Honda',
 523: 'Honda',
 524: 'Nissan',
 525: 'Toyota',
 526: 'Toyota',
 527: 'Toyota',
 528: 'Toyota',
 529: 'BMW',
 530: 'Toyota',
 531: 'Toyota',
 532: 'Nissan',
 533: 'Toyota',
 534: 'Honda',
 535: 'Toyota',
 536: 'Honda',
 537: 'Honda',
 538: 'Nissan',
 539: 'Honda',
 540: 'Honda',
 541: 'Toyota',
 542: 'Toyota',
 543: 'Toyota',
 544: 'Honda',
 545: 'Toyota',
 546: 'Honda',
 547: 'Honda',
 548: 'Toyota',
 549: 'BMW',
 550: 'Toyota',
 551: 'Honda',
 552: 'Honda',
 553: 'Honda',
 554: 'Honda',
 555: 'Honda',
 556: 'Honda',
 557: 'Honda',
 558: 'Honda',
 559: 'Toyota',
 560: 'Honda',
 561: 'Toyota',
 562: 'Toyota',
 563: 'Toyota',
 564: 'Nissan',
 565: 'Toyota',
 566: 'Honda',
 567: 'Toyota',
 568: 'Toyota',
 569: 'Toyota',
 570: 'Toyota',
 571: 'Honda',
 572: 'Toyota',
 573: 'Nissan',
 574: 'Toyota',
 575: 'Honda',
 576: 'Nissan',
 577: 'Toyota',
 578: 'Toyota',
 579: 'Nissan',
 580: 'Nissan',
 581: 'Honda',
 582: 'Honda',
 583: 'Toyota',
 584: 'BMW',
 585: 'Honda',
 586: 'Toyota',
 587: 'Toyota',
 588: 'Honda',
 589: 'Toyota',
 590: 'Toyota',
 591: 'BMW',
 592: 'Honda',
 593: 'Honda',
 594: 'Honda',
 595: 'Honda',
 596: 'Honda',
 597: 'Nissan',
 598: 'Toyota',
 599: 'Honda',
 600: 'Nissan',
 601: 'Toyota',
 602: 'Honda',
 603: 'Nissan',
 604: 'Toyota',
 605: 'Honda',
 606: 'Toyota',
 607: 'Toyota',
 608: 'Honda',
 609: 'Toyota',
 610: 'Honda',
 611: 'Toyota',
 612: 'Honda',
 613: 'Honda',
 614: 'Honda',
 615: 'Honda',
 616: 'Nissan',
 617: 'Nissan',
 618: 'Honda',
 619: 'Honda',
 620: 'BMW',
 621: 'Toyota',
 622: 'Toyota',
 623: 'Honda',
 624: 'Toyota',
 625: 'Honda',
 626: 'Nissan',
 627: 'Nissan',
 628: 'Honda',
 629: 'Honda',
 630: 'Toyota',
 631: 'Nissan',
 632: 'BMW',
 633: 'Nissan',
 634: 'BMW',
 635: 'Honda',
 636: 'Toyota',
 637: 'Toyota',
 638: 'Toyota',
 639: 'Nissan',
 640: 'Honda',
 641: 'Toyota',
 642: 'Toyota',
 643: 'Toyota',
 644: 'Honda',
 645: 'Toyota',
 646: 'Honda',
 647: 'Nissan',
 648: 'Honda',
 649: 'Toyota',
 650: 'Toyota',
 651: 'Nissan',
 652: 'Toyota',
 653: 'Toyota',
 654: 'Toyota',
 655: 'Toyota',
 656: 'Toyota',
 657: 'Toyota',
 658: 'Nissan',
 659: 'Toyota',
 660: 'BMW',
 661: 'BMW',
 662: 'Honda',
 663: 'Honda',
 664: 'BMW',
 665: 'Toyota',
 666: 'Honda',
 667: 'Toyota',
 668: 'Nissan',
 669: 'Nissan',
 670: 'Toyota',
 671: 'Toyota',
 672: 'Toyota',
 673: 'Nissan',
 674: 'BMW',
 675: 'Honda',
 676: 'Toyota',
 677: 'Honda',
 678: 'Toyota',
 679: 'Toyota',
 680: 'Honda',
 681: 'Honda',
 682: 'BMW',
 683: 'Honda',
 684: 'Honda',
 685: 'Toyota',
 686: 'Toyota',
 687: 'Honda',
 688: 'Nissan',
 689: 'Toyota',
 690: 'Nissan',
 691: 'Toyota',
 692: 'Nissan',
 693: 'Nissan',
 694: 'Toyota',
 695: 'Toyota',
 696: 'Honda',
 697: 'Toyota',
 698: 'Nissan',
 699: 'Toyota',
 700: 'Honda',
 701: 'Honda',
 702: 'Honda',
 703: 'Honda',
 704: 'Honda',
 705: 'Toyota',
 706: 'Honda',
 707: 'Nissan',
 708: 'Honda',
 709: 'BMW',
 710: 'Nissan',
 711: 'Honda',
 712: 'Toyota',
 713: 'Toyota',
 714: 'Honda',
 715: 'Toyota',
 716: 'Toyota',
 717: 'Nissan',
 718: 'Honda',
 719: 'Toyota',
 720: 'BMW',
 721: 'Honda',
 722: 'BMW',
 723: 'Toyota',
 724: 'Toyota',
 725: 'Toyota',
 726: 'BMW',
 727: 'Honda',
 728: 'Toyota',
 729: 'Honda',
 730: 'Toyota',
 731: 'Honda',
 732: 'Honda',
 733: 'Toyota',
 734: 'Toyota',
 735: 'Toyota',
 736: 'Toyota',
 737: 'Toyota',
 738: 'Nissan',
 739: 'Honda',
 740: 'BMW',
 741: 'Toyota',
 742: 'BMW',
 743: 'Honda',
 744: 'Toyota',
 745: 'Honda',
 746: 'BMW',
 747: 'Toyota',
 748: 'Toyota',
 749: 'Toyota',
 750: 'Honda',
 751: 'Nissan',
 752: 'Toyota',
 753: 'BMW',
 754: 'BMW',
 755: 'Toyota',
 756: 'Toyota',
 757: 'Nissan',
 758: 'Toyota',
 759: 'Nissan',
 760: 'Nissan',
 761: 'Nissan',
 762: 'Toyota',
 763: 'Honda',
 764: 'Toyota',
 765: 'Honda',
 766: 'Toyota',
 767: 'Nissan',
 768: 'Honda',
 769: 'Honda',
 770: 'Toyota',
 771: 'Honda',
 772: 'Toyota',
 773: 'Toyota',
 774: 'Toyota',
 775: 'Honda',
 776: 'Toyota',
 777: 'Honda',
 778: 'Toyota',
 779: 'BMW',
 780: 'Toyota',
 781: 'Honda',
 782: 'Nissan',
 783: 'Toyota',
 784: 'Honda',
 785: 'Honda',
 786: 'BMW',
 787: 'Toyota',
 788: 'Toyota',
 789: 'Toyota',
 790: 'Honda',
 791: 'Nissan',
 792: 'Toyota',
 793: 'BMW',
 794: 'Toyota',
 795: 'Toyota',
 796: 'Toyota',
 797: 'Toyota',
 798: 'Toyota',
 799: 'Toyota',
 800: 'Honda',
 801: 'Honda',
 802: 'Honda',
 803: 'Toyota',
 804: 'Toyota',
 805: 'Toyota',
 806: 'Nissan',
 807: 'Toyota',
 808: 'Toyota',
 809: 'Toyota',
 810: 'Nissan',
 811: 'BMW',
 812: 'Toyota',
 813: 'Toyota',
 814: 'BMW',
 815: 'Honda',
 816: 'Nissan',
 817: 'Toyota',
 818: 'Honda',
 819: 'Toyota',
 820: 'Honda',
 821: 'Nissan',
 822: 'Nissan',
 823: 'Toyota',
 824: 'Toyota',
 825: 'Nissan',
 826: 'Honda',
 827: 'Honda',
 828: 'Toyota',
 829: 'Honda',
 830: 'Toyota',
 831: 'BMW',
 832: 'Toyota',
 833: 'BMW',
 834: 'Toyota',
 835: 'Toyota',
 836: 'Nissan',
 837: 'BMW',
 838: 'Nissan',
 839: 'Toyota',
 840: 'Honda',
 841: 'Honda',
 842: 'Nissan',
 843: 'Toyota',
 844: 'BMW',
 845: 'Toyota',
 846: 'Toyota',
 847: 'Honda',
 848: 'Toyota',
 849: 'Toyota',
 850: 'Toyota',
 851: 'Toyota',
 852: 'BMW',
 853: 'Nissan',
 854: 'Nissan',
 855: 'Honda',
 856: 'Toyota',
 857: 'BMW',
 858: 'Nissan',
 859: 'Nissan',
 860: 'Toyota',
 861: 'BMW',
 862: 'Honda',
 863: 'Toyota',
 864: 'Honda',
 865: 'Toyota',
 866: 'BMW',
 867: 'BMW',
 868: 'Toyota',
 869: 'Honda',
 870: 'Toyota',
 871: 'Honda',
 872: 'Toyota',
 873: 'Toyota',
 874: 'Toyota',
 875: 'Honda',
 876: 'Honda',
 877: 'Toyota',
 878: 'Toyota',
 879: 'Honda',
 880: 'Honda',
 881: 'Toyota',
 882: 'BMW',
 883: 'Toyota',
 884: 'BMW',
 885: 'Toyota',
 886: 'Toyota',
 887: 'Nissan',
 888: 'BMW',
 889: 'Toyota',
 890: 'Toyota',
 891: 'Nissan',
 892: 'Toyota',
 893: 'Toyota',
 894: 'Honda',
 895: 'Nissan',
 896: 'Toyota',
 897: 'Toyota',
 898: 'Toyota',
 899: 'Toyota',
 900: 'Nissan',
 901: 'Nissan',
 902: 'BMW',
 903: 'Toyota',
 904: 'Toyota',
 905: 'Honda',
 906: 'BMW',
 907: 'BMW',
 908: 'Nissan',
 909: 'BMW',
 910: 'Nissan',
 911: 'Nissan',
 912: 'Nissan',
 913: 'Nissan',
 914: 'Honda',
 915: 'BMW',
 916: 'Honda',
 917: 'Toyota',
 918: 'Honda',
 919: 'Honda',
 920: 'Nissan',
 921: 'Toyota',
 922: 'Honda',
 923: 'Honda',
 924: 'Nissan',
 925: 'Toyota',
 926: 'Honda',
 927: 'Nissan',
 928: 'BMW',
 929: 'Honda',
 930: 'Nissan',
 931: 'Toyota',
 932: 'Toyota',
 933: 'Toyota',
 934: 'Honda',
 935: 'Nissan',
 936: 'Honda',
 937: 'Toyota',
 938: 'Honda',
 939: 'Nissan',
 940: 'Honda',
 941: 'Toyota',
 942: 'Nissan',
 943: 'Toyota',
 944: 'Toyota',
 945: 'BMW',
 946: 'Toyota',
 947: 'Toyota',
 948: 'Toyota',
 949: 'Nissan',
 950: 'Honda',
 951: 'Honda',
 952: 'Nissan',
 953: 'BMW',
 954: 'Toyota',
 955: 'Toyota',
 956: 'Toyota',
 957: 'Nissan',
 958: 'Honda',
 959: 'Nissan',
 960: 'Honda',
 961: 'Toyota',
 962: 'Honda',
 963: 'Toyota',
 964: 'Toyota',
 965: 'Honda',
 966: 'Honda',
 967: 'BMW',
 968: 'Nissan',
 969: 'BMW',
 970: 'Toyota',
 971: 'BMW',
 972: 'Honda',
 973: 'Honda',
 974: 'Toyota',
 975: 'Honda',
 976: 'Toyota',
 977: 'Toyota',
 978: 'BMW',
 979: 'Toyota',
 980: 'Toyota',
 981: 'Toyota',
 982: 'Honda',
 983: 'Toyota',
 984: 'Nissan',
 985: 'Toyota',
 986: 'Honda',
 987: 'Honda',
 988: 'Nissan',
 989: 'Toyota',
 990: 'Toyota',
 991: 'Honda',
 992: 'Honda',
 993: 'Nissan',
 994: 'BMW',
 995: 'Toyota',
 996: 'Toyota',
 997: 'Nissan',
 998: 'Honda',
 999: 'Toyota'}

In [58]:
df['Price'].value_counts()

Price
18184.8    2
19822.8    2
7994.0     2
11648.0    2
7813.0     2
          ..
38450.4    1
5716.0     1
37884.0    1
4001.0     1
12732.0    1
Name: count, Length: 934, dtype: int64

In [59]:
df['Price'].value_counts(bins=[0,5000,10e3,20e3])

(10000.0, 20000.0]    311
(5000.0, 10000.0]     223
(-0.001, 5000.0]       36
Name: count, dtype: int64

In [63]:
df.rename({"Odometer (KM)":"Odometer"}, axis=1)

       Make Colour  Odometer  Doors    Price    Price2
0     Honda  White   35431.0    4.0  18387.6  22065.12
1       BMW   Blue  192714.0    5.0  23931.6  28717.92
2     Honda  White   84714.0    4.0  34011.6  40813.92
3    Toyota  White  154365.0    4.0  13434.0  13434.00
4    Nissan   Blue  181577.0    3.0  14043.0  14043.00
..      ...    ...       ...    ...      ...       ...
995  Toyota  Black   35820.0    4.0  38450.4  46140.48
996  Toyota  White  155144.0    3.0   5716.0   5716.00
997  Nissan   Blue   66604.0    4.0  37884.0  45460.80
998   Honda  White  215883.0    4.0   4001.0   4001.00
999  Toyota   Blue  248360.0    4.0  12732.0  12732.00

[1000 rows x 6 columns]

In [69]:
df = df.sort_values('Price', na_position ='first')
df

       Make Colour  Odometer (KM)  Doors    Price    Price2
119     BMW  White        18394.0    5.0      NaN       NaN
152  Toyota  White        66538.0    4.0      NaN       NaN
171  Toyota  White        97036.0    4.0      NaN       NaN
176  Toyota   Blue        94916.0    4.0      NaN       NaN
249     BMW    Red        33911.0    5.0      NaN       NaN
..      ...    ...            ...    ...      ...       ...
272     BMW  White        23996.0    5.0  57886.8  69464.16
978     BMW  White        85739.0    5.0  58102.8  69723.36
55      BMW  White        79937.0    5.0  58423.2  70107.84
720     BMW  White        57905.0    3.0  61041.6  73249.92
906     BMW  White        16274.0    5.0  62949.6  75539.52

[1000 rows x 6 columns]

In [72]:
df.sort_values('Price', na_position ='last', inplace=True)

In [107]:
df.dropna(thresh=6, axis=0)

       Make Colour  Odometer (KM)  Doors    Price    Price2
757  Nissan   Blue       233501.0    4.0   2796.0   2796.00
845  Toyota  Green       243177.0    4.0   3125.0   3125.00
173  Nissan  Black       240536.0    4.0   3247.0   3247.00
406   Honda   Blue       210446.0    4.0   3594.0   3594.00
678  Toyota  Green       213861.0    4.0   3751.0   3751.00
..      ...    ...            ...    ...      ...       ...
272     BMW  White        23996.0    5.0  57886.8  69464.16
978     BMW  White        85739.0    5.0  58102.8  69723.36
55      BMW  White        79937.0    5.0  58423.2  70107.84
720     BMW  White        57905.0    3.0  61041.6  73249.92
906     BMW  White        16274.0    5.0  62949.6  75539.52

[816 rows x 6 columns]

In [ ]:
df[~df.duplicated()]

       Make Colour  Odometer (KM)  Doors   Price  Price2
757  Nissan   Blue       233501.0    4.0  2796.0  2796.0
845  Toyota  Green       243177.0    4.0  3125.0  3125.0
173  Nissan  Black       240536.0    4.0  3247.0  3247.0
86   Nissan   Blue            NaN    4.0  3300.0  3300.0
700   Honda    NaN       203447.0    4.0  3509.0  3509.0
..      ...    ...            ...    ...     ...     ...
940   Honda  White        53474.0    4.0     NaN     NaN
947  Toyota   Blue        17609.0    4.0     NaN     NaN
952  Nissan  White       136022.0    4.0     NaN     NaN
959  Nissan  White       186786.0    4.0     NaN     NaN
968  Nissan  White       227278.0    4.0     NaN     NaN

[999 rows x 6 columns]

In [120]:
from sqlalchemy import create_engine

query_emp = """
SELECT * 
FROM employees   
limit 100;
"""
query_sal = """
SELECT * 
FROM salaries  
limit 100;
"""

con = create_engine("postgresql+psycopg2://postgres:postgres@localhost/employees")

df_emp = pd.read_sql_query(query_emp, con)
df_sal = pd.read_sql_query(query_sal, con)

In [122]:
df_sal.head(3)

   emp_no  salary   from_date     to_date
0   10001   60117  1986-06-26  1987-06-26
1   10001   62102  1987-06-26  1988-06-25
2   10001   66074  1988-06-25  1989-06-25

In [131]:
df_sal['gender'] = 'M'
df_sal.head(3)

   emp_no  salary   from_date     to_date gender
0   10001   60117  1986-06-26  1987-06-26      M
1   10001   62102  1987-06-26  1988-06-25      M
2   10001   66074  1988-06-25  1989-06-25      M

In [136]:
df_sal.set_index('emp_no', inplace=True)

In [137]:
df_sal

        salary   from_date     to_date gender
emp_no
10001    60117  1986-06-26  1987-06-26      M
10001    62102  1987-06-26  1988-06-25      M
10001    66074  1988-06-25  1989-06-25      M
10001    66596  1989-06-25  1990-06-25      M
10001    66961  1990-06-25  1991-06-25      M
...        ...         ...         ...    ...
10009    74612  1992-02-17  1993-02-16      M
10009    76518  1993-02-16  1994-02-16      M
10009    78335  1994-02-16  1995-02-16      M
10009    80944  1995-02-16  1996-02-16      M
10009    82507  1996-02-16  1997-02-15      M

[100 rows x 4 columns]

In [123]:
df_emp.head(3)

   emp_no  birth_date first_name last_name gender   hire_date
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28

In [138]:
df_emp.set_index("emp_no", inplace=True)

In [135]:
pd.merge(df_emp, df_sal, how='right', left_on='emp_no', right_on='emp_no', suffixes=['_emp', '_sal'])

,emp_no,birth_date,first_name,last_name,gender_emp,hire_date,salary,from_date,to_date,gender_sal
0,10001,1953-09-02,Georgi,Facello,M,1986-06-26,60117,1986-06-26,1987-06-26,M
1,10001,1953-09-02,Georgi,Facello,M,1986-06-26,62102,1987-06-26,1988-06-25,M
2,10001,1953-09-02,Georgi,Facello,M,1986-06-26,66074,1988-06-25,1989-06-25,M
3,10001,1953-09-02,Georgi,Facello,M,1986-06-26,66596,1989-06-25,1990-06-25,M
4,10001,1953-09-02,Georgi,Facello,M,1986-06-26,66961,1990-06-25,1991-06-25,M
...,...,...,...,...,...,...,...,...,...,...
95,10009,1952-04-19,Sumant,Peac,F,1985-02-18,74612,1992-02-17,1993-02-16,M
96,10009,1952-04-19,Sumant,Peac,F,1985-02-18,76518,1993-02-16,1994-02-16,M
97,10009,1952-04-19,Sumant,Peac,F,1985-02-18,78335,1994-02-16,1995-02-16,M
98,10009,1952-04-19,Sumant,Peac,F,1985-02-18,80944,1995-02-16,1996-02-16,M
99,10009,1952-04-19,Sumant,Peac,F,1985-02-18,82507,1996-02-16,1997-02-15,M

In [139]:
pd.merge(df_emp, df_sal, how='left', left_index=True, right_index=True, suffixes=['_emp', '_sal'])

,birth_date,first_name,last_name,gender_emp,hire_date,salary,from_date,to_date,gender_sal
emp_no,,,,,,,,,
10001,1953-09-02,Georgi,Facello,M,1986-06-26,60117.0,1986-06-26,1987-06-26,M
10001,1953-09-02,Georgi,Facello,M,1986-06-26,62102.0,1987-06-26,1988-06-25,M
10001,1953-09-02,Georgi,Facello,M,1986-06-26,66074.0,1988-06-25,1989-06-25,M
10001,1953-09-02,Georgi,Facello,M,1986-06-26,66596.0,1989-06-25,1990-06-25,M
10001,1953-09-02,Georgi,Facello,M,1986-06-26,66961.0,1990-06-25,1991-06-25,M
...,...,...,...,...,...,...,...,...,...
10096,1954-09-16,Jayson,Mandell,M,1990-01-14,NaN,NaN,NaN,NaN
10097,1952-02-27,Remzi,Waschkowski,M,1990-09-15,NaN,NaN,NaN,NaN
10098,1961-09-23,Sreekrishna,Servieres,F,1985-05-13,NaN,NaN,NaN,NaN
10099,1956-05-25,Valter,Sullins,F,1988-10-18,NaN,NaN,NaN,NaN
10100,1953-04-21,Hironobu,Haraldson,F,1987-09-21,NaN,NaN,NaN,NaN

In [142]:
len(df_emp), len(df_sal)

(100, 100)

In [147]:
df_emp.reset_index(inplace=True)
df_sal.reset_index(inplace=True)

In [148]:
pd.concat([df_emp, df_sal], axis = 1)

,emp_no,birth_date,first_name,last_name,gender,hire_date,emp_no,salary,from_date,to_date,gender
0,10001,1953-09-02,Georgi,Facello,M,1986-06-26,10001,60117,1986-06-26,1987-06-26,M
1,10002,1964-06-02,Bezalel,Simmel,F,1985-11-21,10001,62102,1987-06-26,1988-06-25,M
2,10003,1959-12-03,Parto,Bamford,M,1986-08-28,10001,66074,1988-06-25,1989-06-25,M
3,10004,1954-05-01,Chirstian,Koblick,M,1986-12-01,10001,66596,1989-06-25,1990-06-25,M
4,10005,1955-01-21,Kyoichi,Maliniak,M,1989-09-12,10001,66961,1990-06-25,1991-06-25,M
...,...,...,...,...,...,...,...,...,...,...,...
95,10096,1954-09-16,Jayson,Mandell,M,1990-01-14,10009,74612,1992-02-17,1993-02-16,M
96,10097,1952-02-27,Remzi,Waschkowski,M,1990-09-15,10009,76518,1993-02-16,1994-02-16,M
97,10098,1961-09-23,Sreekrishna,Servieres,F,1985-05-13,10009,78335,1994-02-16,1995-02-16,M
98,10099,1956-05-25,Valter,Sullins,F,1988-10-18,10009,80944,1995-02-16,1996-02-16,M
99,10100,1953-04-21,Hironobu,Haraldson,F,1987-09-21,10009,82507,1996-02-16,1997-02-15,M

In [153]:
from sqlalchemy import create_engine

query_emp = """
SELECT gender, count(*) 
FROM employees 
GROUP BY gender;
"""

con = create_engine("postgresql+psycopg2://postgres:postgres@localhost/employees")

df_emp = pd.read_sql_query(query_emp, con)
df_emp

  gender   count
0      M  179973
1      F  120051

In [154]:
from sqlalchemy import create_engine

query_emp = """
SELECT * 
FROM employees   
limit 1000;
"""

con = create_engine("postgresql+psycopg2://postgres:postgres@localhost/employees")

df_emp = pd.read_sql_query(query_emp, con)
df_emp

     emp_no  birth_date first_name     last_name gender   hire_date
0     10001  1953-09-02     Georgi       Facello      M  1986-06-26
1     10002  1964-06-02    Bezalel        Simmel      F  1985-11-21
2     10003  1959-12-03      Parto       Bamford      M  1986-08-28
3     10004  1954-05-01  Chirstian       Koblick      M  1986-12-01
4     10005  1955-01-21    Kyoichi      Maliniak      M  1989-09-12
..      ...         ...        ...           ...    ...         ...
995   10996  1955-02-01       Matk        Rahimi      F  1990-02-07
996   10997  1959-08-30     Alselm  Parascandalo      F  1994-05-06
997   10998  1956-02-17      Marlo       Kandlur      M  1992-06-28
998   10999  1961-12-04      Insup    Benveniste      F  1996-03-05
999   11000  1960-09-12      Alain      Bonifati      M  1988-08-20

[1000 rows x 6 columns]

In [ ]:
df_g = (
	df_emp
	.groupby(by=['gender'], as_index=False)
	['emp_no']
	.count()
	.rename(columns={'emp_no':'c'})
)

  gender    c
0      F  390
1      M  610

In [167]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_no      100 non-null    int64
 1   birth_date  100 non-null    object
 2   first_name  100 non-null    str
 3   last_name   100 non-null    str
 4   gender      100 non-null    str
 5   hire_date   100 non-null    object
dtypes: int64(1), object(2), str(3)
memory usage: 4.8+ KB

In [168]:
df_emp['hire_date'] = pd.to_datetime(df_emp['hire_date'])
df_emp

     emp_no  birth_date first_name     last_name gender  hire_date
0     10001  1953-09-02     Georgi       Facello      M 1986-06-26
1     10002  1964-06-02    Bezalel        Simmel      F 1985-11-21
2     10003  1959-12-03      Parto       Bamford      M 1986-08-28
3     10004  1954-05-01  Chirstian       Koblick      M 1986-12-01
4     10005  1955-01-21    Kyoichi      Maliniak      M 1989-09-12
..      ...         ...        ...           ...    ...        ...
995   10996  1955-02-01       Matk        Rahimi      F 1990-02-07
996   10997  1959-08-30     Alselm  Parascandalo      F 1994-05-06
997   10998  1956-02-17      Marlo       Kandlur      M 1992-06-28
998   10999  1961-12-04      Insup    Benveniste      F 1996-03-05
999   11000  1960-09-12      Alain      Bonifati      M 1988-08-20

[1000 rows x 6 columns]

In [172]:
df['year'] = df_emp['hire_date'].dt.year
df

    emp_no  birth_date   first_name    last_name gender   hire_date  year
0    10001  1953-09-02       Georgi      Facello      M  1986-06-26  1986
1    10002  1964-06-02      Bezalel       Simmel      F  1985-11-21  1985
2    10003  1959-12-03        Parto      Bamford      M  1986-08-28  1986
3    10004  1954-05-01    Chirstian      Koblick      M  1986-12-01  1986
4    10005  1955-01-21      Kyoichi     Maliniak      M  1989-09-12  1989
..     ...         ...          ...          ...    ...         ...   ...
95   10096  1954-09-16       Jayson      Mandell      M  1990-01-14  1990
96   10097  1952-02-27        Remzi  Waschkowski      M  1990-09-15  1990
97   10098  1961-09-23  Sreekrishna    Servieres      F  1985-05-13  1985
98   10099  1956-05-25       Valter      Sullins      F  1988-10-18  1988
99   10100  1953-04-21     Hironobu    Haraldson      F  1987-09-21  1987

[100 rows x 7 columns]

In [ ]:
df.groupby(by='year')

In [180]:
df = (
	df_sal
	.groupby(by='gender', as_index=False)
	[['salary']]
	.mean()
)